@extends('layout')
@section('content')
<main>
<section class="hero snap-section" id="home">
    <div class="hero-copy" data-reveal><span class="eyebrow"><span class="status-dot"></span>Take notes. Leave the effort.</span><h1>Ideas. Notes. Clarity.<br>Wherever your<br class="mobile-break"> mind goes.</h1><p>Your passing thoughts. Your next big thing.<br>One beautifully simple space to bring it all together.</p>
    <div class="style-toolbar" aria-label="Preview heading style"><button data-style="sans" class="style-select">Style 01</button><span class="toolbar-divider"></span><button data-style="bold" aria-label="Toggle bold heading"><b>B</b></button><button data-style="italic" aria-label="Toggle italic heading"><i>I</i></button><button data-style="serif" aria-label="Toggle serif heading">T<span class="tiny">T</span></button><span class="toolbar-divider"></span><button data-style="color" class="color-button" aria-label="Toggle heading color"><span></span></button><button data-style="reset" aria-label="Reset heading style">&#8634;</button></div>
    <div class="hero-actions"><a class="button dark" href="/notes">Find your flow</a><a class="button light" href="#how-it-works">Take a little tour</a></div><span class="hero-caption">Free to start. A little lighter already.</span></div>
    <div class="mountain-scene" aria-hidden="true"><img src="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1800&q=85" alt="" fetchpriority="high"><div class="mountain-fog"></div></div>
</section>
<div class="trust-strip"><span>Small tool. <strong>Endless possibilities.</strong></span><span>&#10023; &nbsp; Your ideas, your space</span><span>&#10023; &nbsp; Beautifully distraction-free</span><span>&#10023; &nbsp; Ready when inspiration hits</span></div>
<section class="section notes-preview snap-section" id="features">
    <div class="section-heading" data-reveal><div><span class="section-label">01 / A CLEARER HEAD</span><h2>Notes that work<br>the way you think.</h2></div><p>A thought shouldn’t get lost in a sea of tabs.<br>Give every idea a home, with a workspace that<br>feels a little more like you.</p></div>
    <div class="editor-stage" data-reveal><div class="floating-label label-left">A little less chaos <span aria-hidden="true">&#8599;</span></div><div class="editor-window"><div class="editor-toolbar"><span class="window-dots">&#9679; &#9679; &#9679;</span><span>My little corner of the internet</span><span aria-hidden="true">&#8599;</span></div><div class="editor-inner"><aside class="preview-sidebar"><span class="mini-brand">n&#8599; &nbsp; My workspace</span><span class="selected">&#9635; &nbsp; All notes <small>12</small></span><span>&#9734; &nbsp; Favorites</span><span>&#9633; &nbsp; Personal</span><span>&#9633; &nbsp; The next big thing</span><span class="sidebar-bottom">+ &nbsp; New collection</span></aside><div class="preview-document"><span class="document-meta">PERSONAL &nbsp; / &nbsp; A FRESH PAGE</span><h3>A little room to think.</h3><p>Some of the best ideas start with a simple thought.<br>No perfect words needed. Just a place to begin.</p><h4>Things I’m making space for</h4><label><input type="checkbox" checked> The ideas that won’t leave my head</label><label><input type="checkbox" checked> Slower mornings. Better questions.</label><label><input type="checkbox"> Something I haven’t thought of yet</label><blockquote>“Almost everything will work again if you unplug it for a few minutes, including you.”</blockquote><div class="document-bottom"><span>Just you and your thoughts.</span><a href="/notes">Make it yours &#8599;</a></div></div></div></div><div class="floating-label label-right">Your ideas look good here &#10023;</div></div>
    <div class="feature-bottom" data-reveal><span>&#10023; &nbsp; Capture the thought. Keep the feeling.</span><a class="text-link" href="/notes">Meet your new workspace &#8599;</a></div>
</section>
<section class="section platforms snap-section" id="platforms"><div class="section-heading" data-reveal><div><span class="section-label">02 / ALWAYS WITH YOU</span><h2>Different screens.<br>Same headspace.</h2></div><p>At your desk. On your way. Somewhere in between.<br>Your next idea doesn’t wait for the right moment.<br>Neither should your notes.</p></div><div class="platform-grid">
<a class="platform-card" href="/notes" data-reveal><div class="platform-art art-phone"><span class="art-tag">Keep it simple.</span><div class="phone"><span class="phone-notch"></span><span class="phone-time">9:41</span><span class="phone-title">Good morning.<br>What’s on your mind?</span><div class="phone-note">&#10023; &nbsp; A small, good idea <i></i><i></i></div><div class="phone-note">&#10023; &nbsp; A little life lately <i></i></div><span class="phone-plus">+</span></div><span class="art-scribble">&#8627;</span></div><div class="card-caption"><div><h3>For your on-the-go thoughts.</h3><p>Your pocket-sized space for inspiration.<br>Open in your Android or iOS browser.</p></div><span class="circle-arrow" aria-hidden="true">&#8599;</span></div></a>
<a class="platform-card" href="/notes" data-reveal><div class="platform-art art-stack"><div class="stack-note"><span aria-hidden="true">&#8599;</span><div>Ideas captured<i></i></div><b>24</b></div><div class="stack-note"><span aria-hidden="true">&#8599;</span><div>A little more organized<i></i></div><b>08</b></div><div class="stack-note"><span aria-hidden="true">&#8599;</span><div>Room for what’s next<i></i></div><b>8</b></div></div><div class="card-caption"><div><h3>A home for the bigger picture.</h3><p>Settle in, spread out, and connect the dots.<br>Made for your desktop browser.</p></div><span class="circle-arrow" aria-hidden="true">&#8599;</span></div></a>
<a class="platform-card" href="/notes" data-reveal><div class="platform-art art-keys"><div class="key-row"><span aria-hidden="true">&#8599;</span><span aria-hidden="true">&#8599;</span><span aria-hidden="true">&#8599;</span><span aria-hidden="true">&#8599;</span></div><div class="pedestal"><span>n&#8599;</span></div><span class="art-tag">Less friction. More flow.</span></div><div class="card-caption"><div><h3>Right at home on your desktop.</h3><p>Windows, Mac, or Linux. Just open a tab<br>and let your thoughts find their rhythm.</p></div><span class="circle-arrow" aria-hidden="true">&#8599;</span></div></a>
<a class="platform-card" href="/notes" data-reveal><div class="platform-art art-orbit"><div class="orbit orbit-one"><i></i></div><div class="orbit orbit-two"><i></i></div><div class="orbit-center">&#10035;</div><span class="art-tag orbit-tag-one">Simply open.</span><span class="art-tag orbit-tag-two">Simply yours.</span></div><div class="card-caption"><div><h3>One tab. A world of possibilities.</h3><p>No downloads. No extra steps.<br>Your browser is all you need.</p></div><span class="circle-arrow" aria-hidden="true">&#8599;</span></div></a>
</div></section>
<section class="section pricing snap-section" id="pricing"><div class="section-heading" data-reveal><div><span class="section-label">03 / SMALL INVESTMENT. BIG IDEAS.</span><h2>A little space.<br>A plan that fits.</h2></div><div><p>Start with a thought. Grow at your own pace.<br>Simple plans for wherever your ideas take you.</p><div class="billing-toggle" aria-label="Billing period"><button class="active" data-billing="yearly" aria-pressed="true">Yearly <span>Save 20%</span></button><button data-billing="monthly" aria-pressed="false">Monthly</button></div></div></div><div class="pricing-grid" data-reveal>
<article class="price-card"><span class="plan-label">THE FIRST CHAPTER</span><h3>Free</h3><p>For a thought worth keeping.</p><div class="price">$0<span>/ forever</span></div><a class="button light" href="/notes">Start your story</a><ul><li>Unlimited notes in this browser</li><li>A clean, focused writing space</li><li>Instant search & favorites</li><li>Export your notes anytime</li></ul><span class="plan-footnote">No card. No pressure. Just ideas.</span></article>
<article class="price-card featured"><span class="popular">A LITTLE MORE POSSIBILITY &#10023;</span><span class="plan-label">ROOM TO GROW</span><h3>Plus</h3><p>For a mind that keeps moving.</p><div class="price">$<span class="price-number" data-yearly="4" data-monthly="5">4</span><span>/ month</span></div><button class="button dark" data-plan="Plus">Join the Plus waitlist</button><ul><li>Everything in Free</li><li>Sync across your devices</li><li>Collections & custom themes</li><li>Version history for peace of mind</li></ul><span class="plan-footnote billing-note">$48 billed yearly · Coming soon</span></article>
<article class="price-card"><span class="plan-label">BETTER TOGETHER</span><h3>Studio</h3><p>For ideas that bring people together.</p><div class="price">$<span class="price-number" data-yearly="9" data-monthly="12">9</span><span>/ person / month</span></div><button class="button light" data-plan="Studio">Join the Studio waitlist</button><ul><li>Everything in Plus</li><li>Shared team workspaces</li><li>Collaborative note editing</li><li>Thoughtful team permissions</li></ul><span class="plan-footnote billing-note">$108 per person billed yearly · Coming soon</span></article>
</div></section>
<section class="section how-section snap-section" id="how-it-works"><div class="section-heading" data-reveal><div><span class="section-label">04 / LESS NOISE. MORE YOU.</span><h2>A simple space.<br>For a wonderfully busy mind.</h2></div><p>There’s no right way to think.<br>Just a better place to put it all.</p></div><div class="how-grid"><div class="thought-art" data-reveal><span class="thought thought-one">a sudden idea &#10023;</span><span class="thought thought-two">that thing to remember</span><span class="thought thought-three">the next big thing &#8599;</span><div class="idea-box"><span>n&#8599;</span></div><span class="box-shadow"></span></div><div class="how-list" data-reveal><article><span>01</span><div><h3>Catch it before it goes.</h3><p>A passing thought, a grand plan, a grocery list. Open a note and get it down while it’s still yours.</p></div></article><article><span>02</span><div><h3>Find a little order.</h3><p>Give your notes a name. Favorite the important ones. Find that one idea with a quick search.</p></div></article><article><span>03</span><div><h3>Make room for what’s next.</h3><p>Your notes save as you write, right in your browser. Less remembering. More being in the moment.</p></div></article></div></div></section>
<section class="section faq-section" id="faq"><span class="section-label" data-reveal>A FEW LITTLE ANSWERS</span><div class="faq-grid"><h2 data-reveal>Good questions.<br>Simple answers.</h2><div data-reveal><details><summary>Where are my notes saved?<span>+</span></summary><p>Your notes are saved locally in this browser on this device. Export a backup before clearing browser data. Cross-device sync is planned for Plus.</p></details><details><summary>Do I need to create an account?<span>+</span></summary><p>No account needed for the free workspace. Just start writing. Your notes stay in the browser you use.</p></details><details><summary>Can I take my notes with me?<span>+</span></summary><p>Absolutely. Use Export in your workspace to download all your notes as a text file, anytime.</p></details></div></div></section>
<section class="cta-section" data-reveal><span class="cta-spark spark-one">&#10035;</span><span class="section-label">EVERY GREAT IDEA STARTS SOMEWHERE.</span><h2>What’s on your mind?</h2><p>A fresh page. A little breathing room.<br>Let’s see where your thoughts take you.</p><a href="/notes" class="button dark">Make a little space</a><span class="cta-spark spark-two">&#10023;</span></section>
</main>
<dialog id="waitlist-dialog"><form id="waitlist-form"><button type="button" class="dialog-close" aria-label="Close dialog">×</button><span class="section-label">GOOD THINGS TAKE A LITTLE TIME.</span><h2>A little more is coming.</h2><p id="waitlist-copy"></p><label for="waitlist-email">Your email</label><input type="email" id="waitlist-email" placeholder="you@example.com" required maxlength="254"><button class="button dark" type="submit">Keep me in the loop</button><p class="dialog-note">We’ll save your interest with easyNote. No payment required.</p></form></dialog>
@endsection
